[url]
allow = [
    "adamchalmers.com",
    "antoyo.xyz",
    "archive.org",
    "arroyo.dev",
    "bevyengine.org",
    "bytecodealliance.org",
    "cloudflare.com",
    "coredumped.dev",
    "crates.io",
    "docs.rs",
    "dylibso.com",
    "dystroy.org",
    "emi0x7d1.dev",
    "endler.dev",
    "eurorust.eu",
    "extism.org",
    "fasterthanli.me",
    "ferrous-systems.com",
    "frankel.ch",
    "gamedev.rs",
    "gcr.io",
    "github.com",
    "github.io",
    "gitlab.com",
    "godbolt.org",
    "guillaume-gomez.fr",
    "implfuture.dev",
    "itehax.com",
    "kernel.org",
    "lib.rs",
    "lkml.org",
    "lwn.net",
    "medium.com",
    "memorysafety.org",
    "m-ou.se",
    "ncameron.org",
    "nikolaivazquez.com",
    "orhun.dev",
    "postgresml.org",
    "procmarco.com",
    "programmershideaway.xyz",
    "ralfj.de",
    "rimu.dev",
    "rustacean-station.org",
    "rust-lang.org",
    "rust-osdev.com",
    "seanmonstar.com",
    "serokell.io",
    "slint-ui.com",
    "smallcultfollowing.com",
    "stackoverflow.com",
    "sunshowers.io",
    "this-week-in-rust.org",
    "tokio.rs",
    "tweag.io",
    "unicode.org",
    "weiznich.de",
    "without.boats",
    "yoshuawuyts.com",
]
block = [
    "discordapp.com",
    "discord.gg",
    "paypal.me",
    "steamcommunity.com",
    "tiktok.com",
]
