[url]
allow = [
    "acm.org",
    "adamchalmers.com",
    "antoyo.xyz",
    "archive.org",
    "arroyo.dev",
    "arxiv.org",
    "berk.es",
    "bevyengine.org",
    "buckmartin.de",
    "burntsushi.net",
    "bytecodealliance.org",
    "cloudflare.com",
    "coredumped.dev",
    "crates.io",
    "deno.com",
    "docs.rs",
    "dreamwidth.org",
    "dylibso.com",
    "dystroy.org",
    "ecton.dev",
    "emi0x7d1.dev",
    "endler.dev",
    "eurorust.eu",
    "eventhelix.com",
    "extism.org",
    "fasterthanli.me",
    "faultlore.com",
    "ferrous-systems.com",
    "fornjot.app",
    "frankel.ch",
    "gamedev.rs",
    "gcr.io",
    "github.com",
    "github.io",
    "gitlab.com",
    "godbolt.org",
    "greyblake.com",
    "gtk-rs.org",
    "guillaume-gomez.fr",
    "implfuture.dev",
    "itehax.com",
    "jetbrains.com",
    "jonashietala.se",
    "kernel.org",
    "lib.rs",
    "linebender.org",
    "lkml.org",
    "lucumr.pocoo.org",
    "lwn.net",
    "m-ou.se",
    "medium.com",
    "memorysafety.org",
    "metalbear.co",
    "ncameron.org",
    "nickb.dev",
    "nikolaivazquez.com",
    "orhun.dev",
    "pinecone.io",
    "postgresml.org",
    "predr.ag",
    "procmarco.com",
    "programmershideaway.xyz",
    "quarticcat.com",
    "quickwit.io",
    "ralfj.de",
    "redox-os.org",
    "relm4.org",
    "rimu.dev",
    "rust-lang.org",
    "rust-osdev.com",
    "rustacean-station.org",
    "seanmonstar.com",
    "serokell.io",
    "shibjm.blog",
    "shuttle.rs",
    "slint-ui.com",
    "smallcultfollowing.com",
    "stackoverflow.com",
    "sunshowers.io",
    "terminusdb.com",
    "theembeddedrustacean.com",
    "this-week-in-rust.org",
    "tokio.rs",
    "tonari.no",
    "torproject.org",
    "tourofrust.com",
    "tratt.net",
    "tweag.io",
    "unicode.org",
    "warp.dev",
    "weiznich.de",
    "without.boats",
    "xeiaso.net",
    "yoshuawuyts.com",
    "zdimension.fr",
]
block = [
    "discordapp.com",
    "discord.gg",
    "medal.tv",
    "paypal.me",
    "steamcommunity.com",
    "tiktok.com",
]
